In [1]:
import numpy as np

In [2]:
# Numpy arrays

In [3]:
# Creating ndarrays

In [4]:
arr1D = np.array([1.1, 2.2, 3.3, 4.4, 5.5]); arr1D

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [5]:
type(arr1D)

numpy.ndarray

In [6]:
arr2D = np.array([[1, 2], [3, 4]]); arr2D

array([[1, 2],
       [3, 4]])

In [7]:
arr4D = np.array(range(16)).reshape((2, 2, 2, 2)); arr4D

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [8]:
# shape and dtype

In [9]:
arr1D.shape

(5,)

In [10]:
arr2D.shape

(2, 2)

In [11]:
arr4D.shape

(2, 2, 2, 2)

In [12]:
arr4D.dtype

dtype('int64')

In [13]:
arr1D.dtype

dtype('float64')

In [14]:
# numpy methods to create ndarrays

In [15]:
np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.random.randn(2,2)

array([[ 0.40414301,  0.66694399],
       [-1.82783216,  0.60940717]])

In [20]:
# Datatypes

In [21]:
np.array([-1, 0, 1], dtype=np.float128)

array([-1.,  0.,  1.], dtype=float128)

In [22]:
# np.array([-1, 0, 1], dtype=np.bool)
np.array([-1, 0, 1], dtype=bool)

array([ True, False,  True])

In [23]:
arr1D.dtype

dtype('float64')

In [24]:
arr1D.astype(np.int64).dtype

dtype('int64')

In [25]:
arr1D.astype(np.int64)

array([1, 2, 3, 4, 5])

In [26]:
# ndarray operations

In [27]:
arr2D

array([[1, 2],
       [3, 4]])

In [28]:
arr2D * 4

array([[ 4,  8],
       [12, 16]])

In [29]:
2*arr2D + 3*arr2D

array([[ 5, 10],
       [15, 20]])

In [30]:
arr2D ** 2

array([[ 1,  4],
       [ 9, 16]])

In [31]:
arr2D + 10

array([[11, 12],
       [13, 14]])

In [32]:
arr2D.transpose()

array([[1, 3],
       [2, 4]])

In [33]:
arr2D.reshape((4, 1))

array([[1],
       [2],
       [3],
       [4]])

In [34]:
arr = np.random.randn(9).reshape((3,3)); arr

array([[-5.43847449e-04, -3.37506076e-01,  1.12339088e+00],
       [ 8.71162854e-01, -1.27703820e+00, -6.21547642e-01],
       [-7.40531564e-01,  1.64192276e-02,  7.23930023e-01]])

In [35]:
np.min(arr)

-1.2770381952437315

In [36]:
np.abs(arr)

array([[5.43847449e-04, 3.37506076e-01, 1.12339088e+00],
       [8.71162854e-01, 1.27703820e+00, 6.21547642e-01],
       [7.40531564e-01, 1.64192276e-02, 7.23930023e-01]])

In [37]:
arr[1, :] = np.nan; arr

array([[-5.43847449e-04, -3.37506076e-01,  1.12339088e+00],
       [            nan,             nan,             nan],
       [-7.40531564e-01,  1.64192276e-02,  7.23930023e-01]])

In [38]:
np.isnan(arr)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [39]:
arr1 = np.random.randn(9).reshape((3,3)); arr1

array([[ 0.28185997, -0.74690922, -0.22566311],
       [-0.34292308, -1.16309038,  1.23832261],
       [-0.79549157, -0.54584634, -2.60390777]])

In [40]:
arr2 = np.random.randn(9).reshape((3,3)); arr2

array([[-0.57717591, -0.1777847 , -0.78697452],
       [-1.1222907 , -0.73384477,  0.42450484],
       [-0.06493637,  0.65168847,  0.18773567]])

In [41]:
np.greater(arr1, arr2)

array([[ True, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [42]:
arr1 > arr2

array([[ True, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [43]:
# Indexing and slicing in Numpy arrays

In [44]:
# Basic indexing

In [45]:
arr = np.random.randn(3,3); arr

array([[-1.31881335, -2.15548293, -0.19707176],
       [ 0.53635573,  1.70596214, -0.21207505],
       [ 1.06248325,  0.20142043,  1.26312173]])

In [46]:
arr[0]

array([-1.31881335, -2.15548293, -0.19707176])

In [47]:
arr[0][1]

-2.155482925326152

In [48]:
arr[0, 1]

-2.155482925326152

In [49]:
arr[-1]

array([1.06248325, 0.20142043, 1.26312173])

In [50]:
# Slicing

In [51]:
arr[1:]

array([[ 0.53635573,  1.70596214, -0.21207505],
       [ 1.06248325,  0.20142043,  1.26312173]])

In [52]:
arr[1:, :2]

array([[0.53635573, 1.70596214],
       [1.06248325, 0.20142043]])

In [53]:
arr[1:2, -2:-1]

array([[1.70596214]])

In [54]:
arr[:][2]

array([1.06248325, 0.20142043, 1.26312173])

In [55]:
arr[:][:]

array([[-1.31881335, -2.15548293, -0.19707176],
       [ 0.53635573,  1.70596214, -0.21207505],
       [ 1.06248325,  0.20142043,  1.26312173]])

In [56]:
arr1 = arr[1:2]; arr1

array([[ 0.53635573,  1.70596214, -0.21207505]])

In [57]:
arr1[:] = 0; arr1

array([[0., 0., 0.]])

In [58]:
arr

array([[-1.31881335, -2.15548293, -0.19707176],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.06248325,  0.20142043,  1.26312173]])

In [59]:
arr_copy = arr.copy()

In [60]:
arr_copy[1:2] = 1; arr_copy

array([[-1.31881335, -2.15548293, -0.19707176],
       [ 1.        ,  1.        ,  1.        ],
       [ 1.06248325,  0.20142043,  1.26312173]])

In [61]:
arr

array([[-1.31881335, -2.15548293, -0.19707176],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.06248325,  0.20142043,  1.26312173]])

In [62]:
arr[:] = np.nan; arr

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [63]:
# Boolean/conditional indexing

In [64]:
arr = np.random.randn(3,3); arr

array([[-0.07302767, -1.70666373,  0.05609154],
       [ 0.92178801,  0.58041525,  0.89394846],
       [ 0.59295016,  1.14521048,  0.67155195]])

In [65]:
arr < 0

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [66]:
arr[(arr < 0)]

array([-0.07302767, -1.70666373])

In [67]:
(arr > -1) & (arr < 1)

array([[ True, False,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [68]:
arr[((arr > -1) & (arr < 1))]

array([-0.07302767,  0.05609154,  0.92178801,  0.58041525,  0.89394846,
        0.59295016,  0.67155195])

In [69]:
arr[(arr < -1) | (arr > 1)]

array([-1.70666373,  1.14521048])

In [70]:
# Indexing with arrays

In [71]:
arr

array([[-0.07302767, -1.70666373,  0.05609154],
       [ 0.92178801,  0.58041525,  0.89394846],
       [ 0.59295016,  1.14521048,  0.67155195]])

In [72]:
arr[[0, 2]]

array([[-0.07302767, -1.70666373,  0.05609154],
       [ 0.59295016,  1.14521048,  0.67155195]])

In [73]:
arr[[0, 2], [1]]

array([-1.70666373,  1.14521048])

In [74]:
arr[[2, 0]]

array([[ 0.59295016,  1.14521048,  0.67155195],
       [-0.07302767, -1.70666373,  0.05609154]])

In [75]:
# Vectorized computation and data processing

In [76]:
# Mathematical operations

In [77]:
arr

array([[-0.07302767, -1.70666373,  0.05609154],
       [ 0.92178801,  0.58041525,  0.89394846],
       [ 0.59295016,  1.14521048,  0.67155195]])

In [78]:
np.mean(arr)

0.3424738280267651

In [79]:
np.mean(arr, axis=0)

array([0.48057016, 0.00632067, 0.54053065])

In [80]:
np.mean(arr, axis=1)

array([-0.57453328,  0.79871724,  0.80323753])

In [81]:
np.argmax(arr)

7

In [82]:
np.argmax(arr, axis=1)

array([2, 0, 1])

In [83]:
np.cumsum(arr)

array([-0.07302767, -1.7796914 , -1.72359985, -0.80181185, -0.2213966 ,
        0.67255187,  1.26550202,  2.4107125 ,  3.08226445])

In [84]:
np.cumsum(arr, axis=1)

array([[-0.07302767, -1.7796914 , -1.72359985],
       [ 0.92178801,  1.50220326,  2.39615172],
       [ 0.59295016,  1.73816063,  2.40971259]])

In [85]:
# Boolean operations

In [86]:
arr_bool = (arr > -0.5) & (arr < 0.5); arr_bool

array([[ True, False,  True],
       [False, False, False],
       [False, False, False]])

In [87]:
arr_bool.any()

True

In [88]:
arr_bool.any(axis=1)

array([ True, False, False])

In [89]:
arr_bool.all()

False

In [90]:
arr_bool.all(axis=1)

array([False, False, False])

In [91]:
# Sorting

In [92]:
arr1D = np.random.randn(10); arr1D

array([-0.28884115,  1.38129757, -1.14325443, -0.87647717,  0.00424846,
        0.26145916,  0.1123967 , -0.31728915, -1.49673231,  0.34611447])

In [93]:
np.sort(arr1D)

array([-1.49673231, -1.14325443, -0.87647717, -0.31728915, -0.28884115,
        0.00424846,  0.1123967 ,  0.26145916,  0.34611447,  1.38129757])

In [94]:
arr1D

array([-0.28884115,  1.38129757, -1.14325443, -0.87647717,  0.00424846,
        0.26145916,  0.1123967 , -0.31728915, -1.49673231,  0.34611447])

In [95]:
np.argsort(arr1D)

array([8, 2, 3, 7, 0, 4, 6, 5, 9, 1])

In [96]:
arr1D.sort()
np.argsort(arr1D)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
# Searching

In [98]:
arr1 = np.array(range(1, 11)); arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr2 = arr1 * 1000; arr2

array([ 1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
       10000])

In [100]:
cond = np.random.randn(10) > 0; cond

array([False,  True, False,  True, False,  True, False, False,  True,
       False])

In [101]:
np.where(cond, arr1, arr2)

array([ 1000,     2,  3000,     4,  5000,     6,  7000,  8000,     9,
       10000])

In [102]:
# File operations and Numpy arrays

In [103]:
# Text files

In [104]:
arr

array([[-0.07302767, -1.70666373,  0.05609154],
       [ 0.92178801,  0.58041525,  0.89394846],
       [ 0.59295016,  1.14521048,  0.67155195]])

In [105]:
np.savetxt('arr.csv', arr, fmt='%0.2lf', delimiter=',')

In [106]:
!cat arr.csv

-0.07,-1.71,0.06
0.92,0.58,0.89
0.59,1.15,0.67


In [107]:
arr_new = np.loadtxt('arr.csv', delimiter=','); arr_new

array([[-0.07, -1.71,  0.06],
       [ 0.92,  0.58,  0.89],
       [ 0.59,  1.15,  0.67]])

In [108]:
# Binary files

In [109]:
np.save('arr', arr)

In [110]:
!cat arr.npy

�NUMPYv{'descr': '<f8', 'fortran_order': False, 'shape': (3, 3), }                                                          
��\�𱲿e1��~N���KT���?��I�?S?��’�?*&��9��?މԚr��?Z�e8�R�?�%�Z}�?

In [111]:
arr_new = np.load('arr.npy'); arr_new

array([[-0.07302767, -1.70666373,  0.05609154],
       [ 0.92178801,  0.58041525,  0.89394846],
       [ 0.59295016,  1.14521048,  0.67155195]])

In [112]:
arr == arr_new

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])