In [1]:
import numpy as np

In [2]:
# Numpy arrays

In [3]:
# Creating ndarrays

In [4]:
arr1D = np.array([1.1, 2.2, 3.3, 4.4, 5.5]); arr1D

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [5]:
type(arr1D)

numpy.ndarray

In [6]:
arr2D = np.array([[1, 2], [3, 4]]); arr2D

array([[1, 2],
       [3, 4]])

In [7]:
arr4D = np.array(range(16)).reshape((2, 2, 2, 2)); arr4D

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [8]:
# shape and dtype

In [9]:
arr1D.shape

(5,)

In [10]:
arr2D.shape

(2, 2)

In [11]:
arr4D.shape

(2, 2, 2, 2)

In [12]:
arr4D.dtype

dtype('int64')

In [13]:
arr1D.dtype

dtype('float64')

In [14]:
# numpy methods to create ndarrays

In [15]:
np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.random.randn(2,2)

array([[-0.39508223, -0.7850645 ],
       [-1.13234769,  1.43396788]])

In [20]:
# Datatypes

In [21]:
np.array([-1, 0, 1], dtype=np.float128)

array([-1.,  0.,  1.], dtype=float128)

In [24]:
# np.array([-1, 0, 1], dtype=np.bool)
np.array([-1, 0, 1], dtype=bool)

array([ True, False,  True])

In [25]:
arr1D.dtype

dtype('float64')

In [26]:
arr1D.astype(np.int64).dtype

dtype('int64')

In [27]:
arr1D.astype(np.int64)

array([1, 2, 3, 4, 5])

In [28]:
# ndarray operations

In [29]:
arr2D

array([[1, 2],
       [3, 4]])

In [30]:
arr2D * 4

array([[ 4,  8],
       [12, 16]])

In [31]:
2*arr2D + 3*arr2D

array([[ 5, 10],
       [15, 20]])

In [32]:
arr2D ** 2

array([[ 1,  4],
       [ 9, 16]])

In [33]:
arr2D + 10

array([[11, 12],
       [13, 14]])

In [34]:
arr2D.transpose()

array([[1, 3],
       [2, 4]])

In [35]:
arr2D.reshape((4, 1))

array([[1],
       [2],
       [3],
       [4]])

In [36]:
arr = np.random.randn(9).reshape((3,3)); arr

array([[ 0.66188164,  0.43709574,  0.63361639],
       [ 1.13955011,  1.02999551,  0.88032601],
       [-0.9718864 ,  0.05757224, -0.99844213]])

In [37]:
np.min(arr)

-0.9984421254517163

In [38]:
np.abs(arr)

array([[0.66188164, 0.43709574, 0.63361639],
       [1.13955011, 1.02999551, 0.88032601],
       [0.9718864 , 0.05757224, 0.99844213]])

In [39]:
arr[1, :] = np.nan; arr

array([[ 0.66188164,  0.43709574,  0.63361639],
       [        nan,         nan,         nan],
       [-0.9718864 ,  0.05757224, -0.99844213]])

In [40]:
np.isnan(arr)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [41]:
arr1 = np.random.randn(9).reshape((3,3)); arr1

array([[-0.27151671,  0.01926991, -0.98227144],
       [-1.54230414,  0.27613573, -0.54714715],
       [ 1.58735248, -1.06047876,  1.4295657 ]])

In [42]:
arr2 = np.random.randn(9).reshape((3,3)); arr2

array([[-0.56069139,  0.55530945, -0.67368015],
       [ 1.27838218,  1.38197653,  0.75604133],
       [-0.11546535,  1.61133765, -1.07328817]])

In [43]:
np.greater(arr1, arr2)

array([[ True, False, False],
       [False, False, False],
       [ True, False,  True]])

In [44]:
arr1 > arr2

array([[ True, False, False],
       [False, False, False],
       [ True, False,  True]])

In [45]:
# Indexing and slicing in Numpy arrays

In [46]:
# Basic indexing

In [47]:
arr = np.random.randn(3,3); arr

array([[ 0.81095048, -0.42402389, -0.3608469 ],
       [-0.41471257, -0.363125  ,  0.11928297],
       [-0.54503509, -2.52908379,  0.3177041 ]])

In [48]:
arr[0]

array([ 0.81095048, -0.42402389, -0.3608469 ])

In [49]:
arr[0][1]

-0.42402389333459684

In [50]:
arr[0, 1]

-0.42402389333459684

In [51]:
arr[-1]

array([-0.54503509, -2.52908379,  0.3177041 ])

In [52]:
# Slicing

In [53]:
arr[1:]

array([[-0.41471257, -0.363125  ,  0.11928297],
       [-0.54503509, -2.52908379,  0.3177041 ]])

In [54]:
arr[1:, :2]

array([[-0.41471257, -0.363125  ],
       [-0.54503509, -2.52908379]])

In [55]:
arr[1:2, -2:-1]

array([[-0.363125]])

In [56]:
arr[:][2]

array([-0.54503509, -2.52908379,  0.3177041 ])

In [57]:
arr[:][:]

array([[ 0.81095048, -0.42402389, -0.3608469 ],
       [-0.41471257, -0.363125  ,  0.11928297],
       [-0.54503509, -2.52908379,  0.3177041 ]])

In [58]:
arr1 = arr[1:2]; arr1

array([[-0.41471257, -0.363125  ,  0.11928297]])

In [59]:
arr1[:] = 0; arr1

array([[0., 0., 0.]])

In [60]:
arr

array([[ 0.81095048, -0.42402389, -0.3608469 ],
       [ 0.        ,  0.        ,  0.        ],
       [-0.54503509, -2.52908379,  0.3177041 ]])

In [61]:
arr_copy = arr.copy()

In [62]:
arr_copy[1:2] = 1; arr_copy

array([[ 0.81095048, -0.42402389, -0.3608469 ],
       [ 1.        ,  1.        ,  1.        ],
       [-0.54503509, -2.52908379,  0.3177041 ]])

In [63]:
arr

array([[ 0.81095048, -0.42402389, -0.3608469 ],
       [ 0.        ,  0.        ,  0.        ],
       [-0.54503509, -2.52908379,  0.3177041 ]])

In [64]:
arr[:] = np.nan; arr

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [65]:
# Boolean/conditional indexing

In [66]:
arr = np.random.randn(3,3); arr

array([[ 0.50017134,  1.34941333, -0.50256388],
       [ 0.42267228, -0.00975289, -0.51885881],
       [-2.28198646, -0.40463036,  2.70152851]])

In [67]:
arr < 0

array([[False, False,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [68]:
arr[(arr < 0)]

array([-0.50256388, -0.00975289, -0.51885881, -2.28198646, -0.40463036])

In [69]:
(arr > -1) & (arr < 1)

array([[ True, False,  True],
       [ True,  True,  True],
       [False,  True, False]])

In [70]:
arr[((arr > -1) & (arr < 1))]

array([ 0.50017134, -0.50256388,  0.42267228, -0.00975289, -0.51885881,
       -0.40463036])

In [71]:
arr[(arr < -1) | (arr > 1)]

array([ 1.34941333, -2.28198646,  2.70152851])

In [72]:
# Indexing with arrays

In [73]:
arr

array([[ 0.50017134,  1.34941333, -0.50256388],
       [ 0.42267228, -0.00975289, -0.51885881],
       [-2.28198646, -0.40463036,  2.70152851]])

In [74]:
arr[[0, 2]]

array([[ 0.50017134,  1.34941333, -0.50256388],
       [-2.28198646, -0.40463036,  2.70152851]])

In [75]:
arr[[0, 2], [1]]

array([ 1.34941333, -0.40463036])

In [76]:
arr[[2, 0]]

array([[-2.28198646, -0.40463036,  2.70152851],
       [ 0.50017134,  1.34941333, -0.50256388]])

In [77]:
# Vectorized computation and data processing

In [78]:
# Mathematical operations

In [79]:
arr

array([[ 0.50017134,  1.34941333, -0.50256388],
       [ 0.42267228, -0.00975289, -0.51885881],
       [-2.28198646, -0.40463036,  2.70152851]])

In [80]:
np.mean(arr)

0.13955478509075936

In [81]:
np.mean(arr, axis=0)

array([-0.45304761,  0.31167669,  0.56003527])

In [82]:
np.mean(arr, axis=1)

array([ 0.44900693, -0.03531314,  0.00497056])

In [83]:
np.argmax(arr)

8

In [84]:
np.argmax(arr, axis=1)

array([1, 0, 2])

In [85]:
np.cumsum(arr)

array([ 0.50017134,  1.84958467,  1.34702079,  1.76969307,  1.75994019,
        1.24108138, -1.04090509, -1.44553545,  1.25599307])

In [86]:
np.cumsum(arr, axis=1)

array([[ 0.50017134,  1.84958467,  1.34702079],
       [ 0.42267228,  0.41291939, -0.10593942],
       [-2.28198646, -2.68661682,  0.01491169]])

In [87]:
# Boolean operations

In [88]:
arr_bool = (arr > -0.5) & (arr < 0.5); arr_bool

array([[False, False, False],
       [ True,  True, False],
       [False,  True, False]])

In [89]:
arr_bool.any()

True

In [90]:
arr_bool.any(axis=1)

array([False,  True,  True])

In [91]:
arr_bool.all()

False

In [92]:
arr_bool.all(axis=1)

array([False, False, False])

In [93]:
# Sorting

In [94]:
arr1D = np.random.randn(10); arr1D

array([-0.25607928, -0.72842144,  0.46966284,  0.65526565,  0.83516848,
       -1.10404279, -1.06193121, -0.15673139,  0.36822796, -0.94983048])

In [95]:
np.sort(arr1D)

array([-1.10404279, -1.06193121, -0.94983048, -0.72842144, -0.25607928,
       -0.15673139,  0.36822796,  0.46966284,  0.65526565,  0.83516848])

In [96]:
arr1D

array([-0.25607928, -0.72842144,  0.46966284,  0.65526565,  0.83516848,
       -1.10404279, -1.06193121, -0.15673139,  0.36822796, -0.94983048])

In [97]:
np.argsort(arr1D)

array([5, 6, 9, 1, 0, 7, 8, 2, 3, 4])

In [98]:
arr1D.sort()
np.argsort(arr1D)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
# Searching

In [100]:
arr1 = np.array(range(1, 11)); arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr2 = arr1 * 1000; arr2

array([ 1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
       10000])

In [102]:
cond = np.random.randn(10) > 0; cond

array([ True,  True,  True,  True, False, False,  True,  True,  True,
        True])

In [103]:
np.where(cond, arr1, arr2)

array([   1,    2,    3,    4, 5000, 6000,    7,    8,    9,   10])

In [104]:
# File operations and Numpy arrays

In [105]:
# Text files

In [106]:
arr

array([[ 0.50017134,  1.34941333, -0.50256388],
       [ 0.42267228, -0.00975289, -0.51885881],
       [-2.28198646, -0.40463036,  2.70152851]])

In [107]:
np.savetxt('arr.csv', arr, fmt='%0.2lf', delimiter=',')

In [108]:
!cat arr.csv

0.50,1.35,-0.50
0.42,-0.01,-0.52
-2.28,-0.40,2.70


In [109]:
arr_new = np.loadtxt('arr.csv', delimiter=','); arr_new

array([[ 0.5 ,  1.35, -0.5 ],
       [ 0.42, -0.01, -0.52],
       [-2.28, -0.4 ,  2.7 ]])

In [110]:
# Binary files

In [111]:
np.save('arr', arr)

In [112]:
!cat arr.npy

�NUMPYv{'descr': '<f8', 'fortran_order': False, 'shape': (3, 3), }                                                          
vy�Tg�?)o2��?��+����M
�?�n4jR�����;�}��,��A�����v�ٿ<�^���@

In [113]:
arr_new = np.load('arr.npy'); arr_new

array([[ 0.50017134,  1.34941333, -0.50256388],
       [ 0.42267228, -0.00975289, -0.51885881],
       [-2.28198646, -0.40463036,  2.70152851]])

In [114]:
arr == arr_new

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])